api_route: /api/

apis:
  - name: auth.v1.WebAuthService
    cluster: auth_service
    auth: {policy: no-need}
    methods:
      - name: LoginPublic
        auth:
          policy: no-need
          rate_limit: {period: "1m", count: 3, delay: "3s"}
      - name: CheckPasswordPublic
        auth:
          policy: required
          rate_limit: {period: "1m", count: 5, delay: "3s"}
      - name: ChangePasswordPublic
        auth:
          policy: required
          rate_limit: {period: "1m", count: 5, delay: "3s"}
      - name: InitPasswordReset
        auth:
          policy: no-need
          need_recaptcha: true
          rate_limit: {period: "1m", count: 2, delay: "10s"}

clusters:
  - name: auth_service
    addr: "auth_service.svc.cluster.local:9090"
